**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [1]:
import numpy as np

z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [2]:
import numpy as np

# Get input from the user
a = int(input("Enter the number of rows (a): "))
b = int(input("Enter the number of columns (b): "))

# Generate a random array of shape (a, b)
random_array = np.random.rand(a, b)

# Print the array
print("Random Array:")
print(random_array)

# Calculate and print the average of the array
average = np.mean(random_array)
print("\nAverage of the array:", average)

Enter the number of rows (a): 2
Enter the number of columns (b): 2
Random Array:
[[0.46498614 0.71786243]
 [0.63978875 0.31351682]]

Average of the array: 0.5340385380220016


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
import numpy as np

def create_bordered_array(a, b):
  """
  Creates a 2D array with 1 on the border and 0 inside.

  Args:
    a: Number of rows.
    b: Number of columns.

  Returns:
    A 2D NumPy array with the specified shape and border values.
  """

  array = np.ones((a, b))  # Create an array filled with 1s
  array[1:-1, 1:-1] = 0  # Set the inner elements to 0
  return array

# Example usage
a = 4
b = 4
bordered_array = create_bordered_array(a, b)
print(bordered_array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [4]:
import numpy as np

vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [7]:
#No
#you cannot create an identity matrix with a shape of (3, 4). Identity matrices must be square, meaning they have the same number of rows and columns.

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [9]:
import numpy as np

# Given point
point = np.array([2, 3])

# Generate random coordinates
random_coords = np.random.randint(1, 101, size=(10, 2))

# Calculate distances
distances = np.sqrt(np.sum((random_coords - point)**2, axis=1)).astype(int)

print(distances)

[ 81 102  40  79  45 125 115 105  88 124]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [10]:
import numpy as np

index = np.unravel_index(99, (6, 7, 8))  # Use 99 for the 100th element (0-based indexing)
print(index)


(1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [12]:
import numpy as np

# Input: space-separated numbers
numbers_str = input()

# Convert to NumPy array of floats
numbers_array = np.array(numbers_str.split(), dtype=float)

# Reverse the array
reversed_array = numbers_array[::-1]

# Print the reversed array
print(reversed_array)

10 20 30 40
[40. 30. 20. 10.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [13]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])  # Example array
elements_count = array.size

print("elements_count : ", elements_count)

elements_count :  5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [17]:
import numpy as np

def softmax(arr):
    """
    Calculates the Softmax of a given NumPy 1D array.

    Args:
        arr: A NumPy 1D array.

    Returns:
        The Softmax of the input array.

    Raises:
        TypeError: If the input is not a NumPy 1D array.
    """
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise TypeError("Input must be a NumPy 1D array.")

    exp_arr = np.exp(arr)
    return exp_arr / np.sum(exp_arr)

# Example usage
arr = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
softmax_result = softmax(arr)
print(softmax_result)

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [18]:
import numpy as np

def vertical_stack(*arrays):
    """
    Vertically stacks an infinite number of NumPy arrays.

    Args:
        *arrays: Variable number of NumPy arrays.

    Returns:
        The vertically stacked array.

    Raises:
        TypeError: If any input is not a NumPy array.
    """
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays.")

    return np.vstack(arrays)

# Example usage
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

stacked_array = vertical_stack(a, b, c)
print(stacked_array)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [19]:
import numpy as np
from datetime import datetime, timedelta

def date_array(start, end):
    """
    Generates a NumPy array of dates between two given dates.

    Args:
        start (str): The start date in 'YYYY-MM-DD' format.
        end (str): The end date in 'YYYY-MM-DD' format.

    Returns:
        numpy.ndarray: An array of dates between the start and end dates, inclusive.

    Raises:
        TypeError: If start or end is not a string.
    """

    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Start and end dates must be strings.")

    start_date = datetime.strptime(start, '%Y-%m-%d')
    end_date = datetime.strptime(end, '%Y-%m-%d')

    num_days = (end_date - start_date).days + 1  # Include end date

    date_list = [start_date + timedelta(days=i) for i in range(num_days)]
    date_array = np.array([date.strftime('%Y-%m-%d') for date in date_list])

    return date_array

# Example usage
start_date = '2020-09-15'
end_date = '2020-09-25'
date_range = date_array(start_date, end_date)
print(date_range)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [20]:
import numpy as np

# Example array
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2,1]]

# Print the modified array
print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


###`Q-16:` Replace odd elements in arrays with -1.

In [21]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Replace odd elements with -1
arr[arr % 2 != 0] = -1

# Print the modified array
print(arr)


[-1  2 -1  4 -1  6 -1  8 -1 10]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [22]:
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)

print(result)


[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [23]:
import numpy as np

# Given array
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)

# Fetch every alternate column
alternate_cols = arr1[:, ::2]  # Select all rows (:) and every other column (::2)

# Normalize the array
arr1_min = arr1.min()
arr1_max = arr1.max()
normalized_arr = (arr1 - arr1_min) / (arr1_max - arr1_min)

print("Alternate Columns:")
print(alternate_cols)
print("\nNormalized Array:")
print(normalized_arr)

Alternate Columns:
[[5877 9202 8114]
 [2117 6259 9632]
 [2712 4656 8933]
 [1745  165 7664]
 [3297 2993 5466]
 [7264 7100 1937]
 [1630 9314 5085]
 [5165 1676 8603]]

Normalized Array:
[[0.59648401 0.01840239 0.93831603 0.03248689 0.82646242]
 [0.20993112 0.51444433 0.63575614 1.         0.98252287]
 [0.27110106 0.63770947 0.47095713 0.62989617 0.91066105]
 [0.17168706 0.53130462 0.0092526  0.41667523 0.78019944]
 [0.33124293 0.86059422 0.29998972 0.06147836 0.55423049]
 [0.7390768  0.95918577 0.72221651 0.23100648 0.19142593]
 [0.1598643  0.77742367 0.94983037 0.         0.51506117]
 [0.5232857  0.55443611 0.1645934  0.20869744 0.87673486]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [24]:
import numpy as np

def find_nth_largest(arr, n):
  """
  Finds the nth largest element in a 1D NumPy array.

  Args:
    arr: A 1D NumPy array.
    n: The desired position of the largest element (1-based).

  Returns:
    The nth largest element in the array.
  """
  if n > len(arr) or n <=0:
    raise ValueError("Invalid value for n")

  sorted_arr = np.sort(arr)  # Sort the array in ascending order
  return sorted_arr[-n]  # Get the nth largest element (from the end)


# Example usage
arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
nth_largest = find_nth_largest(arr, n)
print(nth_largest)  # Output: 12

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [25]:
import numpy as np

a = np.array([1, 2, 3])

pattern = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])

print(pattern)  # Output: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
